function update_3D_fig(obj, type)
	switch obj.hemi
		case 'L'
			nodesAll = obj.session.lh.nodesAll;
		case 'R'
			nodesAll = obj.session.rh.nodesAll;
	end
	switch type
		case 'corner'
			hThis = obj.h.corner;
			set(hThis,   ...
				'XData', nodesAll(obj.hiResCornerVert(:),2),...
				'YData', nodesAll(obj.hiResCornerVert(:),3),...
				'ZData', nodesAll(obj.hiResCornerVert(:),4),...
				'color', [0 0 0]);
			uistack(hThis, 'bottom');
		case 'edge'
			hThis = obj.h.edge;
			set(hThis,   ...
				'XData', nodesAll(obj.hiResEdgeVert(:),2),...
				'YData', nodesAll(obj.hiResEdgeVert(:),3),...
				'ZData', nodesAll(obj.hiResEdgeVert(:),4),...
				'color', obj.edgeColor);
		case 'surf'
			hThis = obj.h.surf;
			set(hThis,   ...
				'XData', nodesAll(obj.hiResVert(:),2),...
				'YData', nodesAll(obj.hiResVert(:),3),...
				'ZData', nodesAll(obj.hiResVert(:),4),...
				'color', obj.faceColor);
			%                obj.fill_patch_time_fcn();
		otherwise
			error();
	end
end %k
